### ISSUE TITLE
Nvidia-Docker doesn't work on Clarendon

### ISSUE THREAD

**Issue by joshimbriani** [oudalab/lorisal#1]
I have installed nvidia-docker onto Clarendon and am trying to get it to work. The following command is recommended by NVIDIA to test your install.

nvidia-docker run --rm nvidia/cuda nvidia-smi

When running it I get this error:

nvidia-docker | 2017/03/03 18:50:19 Error: Could not load UVM kernel module. Is nvidia-modprobe installed?

I have installed nvidia-modprobe via apt and I still get the same exact message. I have searched the issue and found that it means that the driver isn't working correctly and I have tried updating it and still nothing working.

**Comment by cegme** [comment]
@joshimbriani is this issue resolved? Can you share the fix and close the issue?
